name: U04bMinecraftRoadBuilder

author: Your Name

main: U04bMinecraftRoadBuilder

commands:
    petwolf:
        description: "Spawn a wolf as the player's pet."
    petllama:
        description: "Spawn a pet llama"

version: 1.0